# Generated by Django 4.0.3 on 2022-03-19 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_recipe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='time_minues',
            new_name='time_minutes',
        ),
    ]
